# Generated by Django 2.2.4 on 2019-08-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_category',
        ),
        migrations.AddField(
            model_name='quote',
            name='quote',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
