# Generated by Django 2.2.4 on 2019-08-29 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190829_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quote_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.QuoteCategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quote',
            name='quote',
            field=models.TextField(),
        ),
    ]
